image: ubuntu:xenial
stages:
  - test
job_test:
  stage: test
  script:
  - apt-get update && apt-get install -y apt-utils locales git
  - git clone https://gitlab.com/flectra-hq/build-tools.git ${CI_PROJECT_DIR}/build-tools && export PATH=${CI_PROJECT_DIR}/build-tools/travis:${PATH}
  - travis_install_flectra
  - su - flectra -c "export PATH=${CI_PROJECT_DIR}/build-tools/travis:${PATH} && travis_test_flectra --build=base"
  - su - flectra -c "export PATH=${CI_PROJECT_DIR}/build-tools/travis:${PATH} && travis_test_flectra --build=all"